# Codecov Configuration for Conductor
# See: https://docs.codecov.com/docs/codecov-yaml

# Coverage target and thresholds
coverage:
  precision: 2
  round: down
  range: 70...90

  status:
    project:
      default:
        # Require at least 75% coverage (current: 78.3%)
        target: 75%
        threshold: 2%
        # Only fail if coverage drops by more than 2%
        if_ci_failed: error

    patch:
      default:
        # New code should maintain at least 70% coverage
        target: 70%
        threshold: 5%

# Comment on PRs with coverage changes
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Ignore patterns - exclude test files from coverage calculations
ignore:
  - "**/*_test.go"
  - "**/testdata/**"
  - "**/*.md"
  - ".github/**"

# Flags for different test types (can expand later)
flags:
  unittests:
    paths:
      - internal/
    carryforward: true
